apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-username/argo-cd-config.git
    path: .
    targetRevision: HEAD
    sshPrivateKeySecret:
      name: my-github-ssh-key
      key: sshPrivateKey
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
