apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:rjshrjndrn/argo-or-config
    path: client1/domain.com
    targetRevision: HEAD
    sshPrivateKeySecret:
      name: my-github-ssh-key
      key: sshPrivateKey
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
